name: 'Validation hotfix branch'

runs:
  using: "composite"
  steps:
  - name: Check if branch is up with main
    shell: bash
    run: |
      if [[ "$(git merge-base origin/main HEAD)" == "$(git rev-parse origin/main)" ]] ; then echo 'Branch up to date'; else echo 'Branch outdated' && exit 1; fi
